#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export IP=127.0.0.1
export PORT=4500

function check_response()
{
    data=("$@")
    len=${#data[@]}
    if [ "${len}" != 2 ]; then
        return 1
    else
        #check error code
        if [ "${data[1]}" != 200 ]; then
            return 1
        fi 
    fi

    return 0
}

function print_request_data()
{
    req='{"api":1,"request":'$1'}'

    echo "==========================================="
    echo "Request"
    echo "-------------------------------------------"
    echo ${req} | jq .
}

function print_request_data_no_param()
{
    req='{"api":1}'

    echo "==========================================="
    echo "Request"
    echo "-------------------------------------------"
    echo ${req} | jq .
}

function print_response_data
{
    echo "==========================================="
    echo "Response"
    echo "-------------------------------------------"
    echo $1 | jq .
}

function send_request()
{
    data=$(curl -s -w " %{http_code}" -X GET http://${IP}:${PORT}/$1 \
    -d '{"api":1,"request":'$2'}' \
    -H 'Content-Type: application/json')

    data=(${data[@]})
    check_response ${data[@]}
    ret=$?
    echo ${data[0]}
    return ${ret}
}

function send_request_no_param()
{
    data=$(curl -s -w " %{http_code}" -X GET http://${IP}:${PORT}/$1 \
    -d '{"api":1}' \
    -H 'Content-Type: application/json')

    data=(${data[@]})
    check_response ${data[@]}
    ret=$?
    echo ${data[0]}
    return ${ret}
}
