#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${dir}/_common

key=$1
request='{"key":"'${key}'"}'

data=$(send_request get_message ${request})

print_request_data ${request}
echo ""
print_response_data ${data}

echo ""
echo "==========================================="
echo "Decoded Message"
echo "-------------------------------------------"
# extract the base64 message, trim the quotes and decode
echo $(jq '.response.message' <<< "${data[0]}" | tr -d '"' | base64 --decode )