#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${dir}/_common

data=$(send_request_no_param get_message_details)

print_request_data_no_param
echo ""
print_response_data ${data}