#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${dir}/_common

request='{"private":true}'

data=$(send_request get_address ${request})

print_request_data ${request}
echo ""
print_response_data ${data}