#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${dir}/_common

address=$1
message=$(echo "$2" | tr -d '"' | base64)

request='{"address":"'${address}'","message":"'${message}'"}'

data=$(send_request send_message ${request})

print_request_data ${request}
echo ""
print_response_data ${data}