#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${BUILDER_DIR}/helpers

function clean()
{
    clean_build_artifacts
}

function debug()
{
    dotnet build                    \
    /p:GenerateFullPaths=true       \
    /p:Configuration=Debug          \
    /p:TrimUnusedDependencies=true
}

function release()
{
    dotnet build                    \
    /p:GenerateFullPaths=true       \
    /p:Configuration=Release        \
    /p:TrimUnusedDependencies=true
}

$1
