#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR=$(dirname $BUILDER_DIR)

function detect_version()
{
    ver=$(awk '/public const string VERSION = /{ print $6 }' < ${ROOT_DIR}/Src/EMS/Version.cs)
	name=$(awk '/public const string CODE_NAME = /{ print $6 }' < ${ROOT_DIR}/Src/EMS/Version.cs)
    export APP_VERSION=$(echo ${ver} | tr -d '";')
	export APP_CODENAME=$(echo ${name} | tr -d '";')
    echo App version detected as ${APP_VERSION}: ${APP_CODENAME}
}

function clean_build_artifacts()
{
    find ${ROOT_DIR}/External -iname "bin" -o -iname "obj" | xargs rm -rf
    find ${ROOT_DIR}/Src -iname "bin" -o -iname "obj" | xargs rm -rf
}

function clean()
{
    cd ${ROOT_DIR}
    clean_build_artifacts
}

function debug()
{
    cd ${ROOT_DIR}
    dotnet build                        \
    /p:Configuration=Debug
}

function release()
{
    cd ${ROOT_DIR}
    dotnet build                        \
    /p:Configuration=Release
}

function publish()
{
    cd ${ROOT_DIR}
    dotnet publish                      \
    /p:RuntimeIdentifier=$1-x64         \
    /p:Configuration=Release            \
    /p:Publish=true
}

function publish_all()
{
    publish linux
    publish win
    publish osx

    cd ${ROOT_DIR}/Bin/Release/netcoreapp3.1/linux-x64/publish
    zip ${ROOT_DIR}/Bin/ems-v${APP_VERSION}_linux.zip ./ems

    cd ${ROOT_DIR}/Bin/Release/netcoreapp3.1/win-x64/publish
    zip ${ROOT_DIR}/Bin/ems-v${APP_VERSION}_windows.zip ./ems.exe

    cd ${ROOT_DIR}/Bin/Release/netcoreapp3.1/osx-x64/publish
    zip ${ROOT_DIR}/Bin/ems-v${APP_VERSION}_osx.zip ./ems
}

detect_version

$1 $2
